### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'qk_scale'

### ISSUE THREAD

**Issue by shuaiqidexiaojiejie** [zhangzilongc/MMR#3]
I encountered the following error while running the program you provided. Can you help me resolve it.
TypeError: __init__() got an unexpected keyword argument 'qk_scale'
![图片](https://github.com/zhangzilongc/MMR/assets/101921170/d14ec4c2-a0ed-42b6-ae39-efcdcf84c1cd)

**Comment by zhangzilongc** [comment]
can you check your timm version? The required timm version is timm==0.3.2. This repo is based on `timm==0.3.2`(https://github.com/rwightman/pytorch-image-models), for which a fix (https://github.com/rwightman/pytorch-image-models/issues/420#issuecomment-776459842) is needed to work with PyTorch 1.8.1+.

**Comment by zhangzilongc** [comment]
> I encountered the following error while running the program you provided. Can you help me resolve it. TypeError: **init**() got an unexpected keyword argument 'qk_scale' ![图片](https://user-images.githubusercontent.com/101921170/239735390-d14ec4c2-a0ed-42b6-ae39-efcdcf84c1cd.png)

above

**Comment by shuaiqidexiaojiejie** [comment]
Thank you for your help
